version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "15:c3:00:4a:48:1d:4c:fe:93:df:ef:e9:c2:3f:2c:d9"
      - run:
          name: Deploy app to AWS EC2 via Docker
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-59-234-24.eu-central-1.compute.amazonaws.com "cd production && git pull && /bin/bash deploy_app.sh"

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
